# Generated by Django 4.0.4 on 2022-06-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_otpcodemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
