# Generated by Django 4.0.4 on 2022-06-03 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_ordermodel_options'),
        ('Accounts', '0004_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordernoti', to='category.ordermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernoti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
