# Generated by Django 4.0.5 on 2022-06-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_notifacationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcodemodel',
            name='code',
        ),
    ]
