# Generated by Django 4.0.5 on 2022-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_otpcodemodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcodemodel',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
