# Generated by Django 4.0.5 on 2022-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_companymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
