# Generated by Django 4.0.5 on 2022-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_companymodel_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='national_card',
            field=models.ImageField(upload_to='<django.db.models.fields.related.OneToOneField>/national code'),
        ),
    ]
