# Generated by Django 4.0.4 on 2022-06-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_ordermodel_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ('view',)},
        ),
    ]
