# Generated by Django 4.0.5 on 2022-06-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_brandmodel_productmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbrand', to='category.categorymodel'),
        ),
    ]
