# Generated by Django 4.0.5 on 2022-06-26 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0010_brandmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
