# Generated by Django 4.0.5 on 2022-06-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0011_productmodel_like_alter_brandmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNotModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppnot', to='category.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upnot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
