# Generated by Django 4.0.5 on 2022-06-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_productnotmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnotmodels',
            name='product',
        ),
        migrations.AddField(
            model_name='productnotmodels',
            name='ordertitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opnot', to='category.orderitemsmodel'),
        ),
    ]
