# Generated by Django 4.0.5 on 2022-06-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_remove_productnotmodels_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productnotmodels',
            old_name='ordertitem',
            new_name='orderitem',
        ),
    ]
