# Generated by Django 4.0.5 on 2022-06-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_rename_ordertitem_productnotmodels_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnotmodels',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='productnotmodels',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opnot', to='category.productmodel'),
        ),
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poitem', to='category.productmodel'),
        ),
    ]
