# Generated by Django 4.0.5 on 2022-06-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_orderitemsmodel_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsmodel',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
