# Generated by Django 4.0.5 on 2022-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_orderitemsmodel_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='star',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
