# Generated by Django 4.0.5 on 2022-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_productmodel_special_productmodel_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='img',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
    ]
