# Generated by Django 4.0.5 on 2022-08-06 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0021_remove_productmodel_like_productmodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='like',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
