# Generated by Django 4.0.5 on 2022-08-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_remove_productmodel_like_productmodel_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
