# Generated by Django 4.1 on 2022-08-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0023_productmodel_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='category.categorymodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeproduct', to='category.typeproductmodel'),
        ),
    ]
