# Generated by Django 4.1 on 2022-08-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0027_alter_typeproductmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproductmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
