# Generated by Django 4.1 on 2022-09-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0035_alter_productmodel_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='star',
            field=models.JSONField(default=[]),
        ),
    ]
