# Generated by Django 4.1 on 2022-09-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0038_alter_productmodel_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='star',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
