# Generated by Django 4.0.5 on 2022-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_replaycommentmodel_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaycommentmodel',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
